version: "3.8"

services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-shubhu1026}"
    image: cyber-bullying-detection-template
    platform: linux/amd64
    container_name: cyber-bullying-detection-template-container
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USER_NAME:-shubhu1026}"
        USER_ID: "${USER_ID:-1000}"
    volumes:
      - ./:/app/
      - ~/.config/gcloud/:/home/${USER_NAME:-shubhu1026}/.config/gcloud
    ports:
      - 8080:8080

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host
    init: true

